server:
  port: 9102
  servlet:
    context-path: /api/holmes-engine-mgmt/v1
  ssl:
    key-store: /opt/onap/conf/holmes.keystore
    key-store-password: holmes
    #PKCS12
    key-store-type: JKS

logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: Holmes Engine Management
  datasource:
    dirver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/holmes
    username: holmes
    password: holmespwd
  mvc:
    throw-exception-if-no-handler-found: true